### ISSUE TITLE
Space traveler Kanban setup

### ISSUE THREAD

**Issue by toliboff** [Ghiftee/space-travellers#25]
Link:  https://github.com/Ghiftee/space-travellers
We have two people for this project
StudentA : Tolib
StudentB: Ghiftee

**Comment by arslanbisharat** [comment]
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
- [x] For a team with 2 people number of cards in Backlog should be equal to 17 but I can see you have 24 cards. Please work on the requirements. 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Ghiftee** [comment]
Hello,
Thanks for the review. We have checked our project and we have 17 cards and not 24.
Can you point us to where you made reference to?
Thank you.

**Comment by arslanbisharat** [comment]
> Hello,
> Thanks for the review. We have checked our project and we have 17 cards and not 24.
> Can you point us to where you made reference to?
> Thank you.

Hi there, 
I am sorry for the mistake. Yes you are right you have 17 cards as requirements says. Please accept my apology and request another review.

**Comment by vichuge** [comment]
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
